### ISSUE TITLE
File type: Compability mode. google drive issues

### ISSUE THREAD

**Issue by anderstornoe** [evidenceprime/html-docx-js#32] opened 2016-06-20 08:51 UTC
I really appreciate the work done with html-docx-js! 

However, the docx file opens in compability mode in Word (Mac) and is not able to open i Google Drive for instance. I suspect it is due to compability mode. 

Is there any work arounds here, or plans to address this issue? 

Thanks!

**Comment by N1kto** [comment] 2016-12-08 22:07
Duplicate of #5

**Closed as completed by N1kto** 2016-12-08 22:07 UTC
