### ISSUE TITLE
Running client side

### ISSUE THREAD

**Issue by DirkSimons** [evidenceprime/html-docx-js#78] opened 2018-06-25 09:36 UTC
Is there any way to run this client side?   I keep hitting the `fs.readFileSync is not a function` error when only doing the conversion. (`var converted = htmlDocx.asBlob(content)`) 
Anyone have an idea how to resolve this.

**Comment by anowak** [comment] 2018-06-25 11:53
Duplicate of #51 

In short: you either need to polyfill the `fs` module (using Browserify or something else) or use our bundle with batteries included: `html-docx-js/dist/html-docx`.

**Closed as completed by anowak** 2018-06-25 11:53 UTC
