### ISSUE TITLE
Can't apply border styles to <span> elements?

### ISSUE THREAD

**Issue by george-ionita** [evidenceprime/html-docx-js#67] opened 2017-11-07 12:42 UTC
I can't seem to be able to export the style for span elements. 

`<span style="border-bottom: 2px dotted;">Test</span>` doesn't work.

However  `<h3 style="border-bottom: 2px dotted;">Test</h3>` works.

Any ideas?

**Comment by N1kto** [comment] 2017-11-07 12:52
Try replacing `<span>` in your markup with `<div>` with appropriate _display_ attribute (e.g. _inline-block_). It might be caused by the fact that `<span>` is not a block element by default, so **Word's** render engine doesn't apply border to it.

**Comment by george-ionita** [comment] 2017-11-07 13:42
I've changed it to div but I'm afraid `display: inline-block` doesn't get applied either when exporting. Any other suggestions?

**Comment by N1kto** [comment] 2017-11-07 14:10
Did you try it or is it your assumption? 
Which **Word** version and on which platform are you using? Share the code which could be run to reproduce the issue.

Couldn't reproduce the issue on my **Word 2013**  (Windows10). Text is bordered as expected.
Try opening the attached file in your **Word** application. Do you see red border?
[test.docx](https://github.com/evidenceprime/html-docx-js/files/1450248/test.docx)

**Comment by george-ionita** [comment] 2017-11-07 14:20
I tried it, the bordering works but not "display: inline-block" - the bottom border stretches across a whole line.

It looks right if I copy-paste the HTML code in a file and run it in a browser. 

`            var html_test = '<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body data-id="content"><p><div class="cavacnote" entitycomment="Annotation about Scaramouch" id="1" style="border-bottom: 2px dotted; border-color: #FFA500;display: inline-block;">Test<a class="link" entitycomment_id="2" id="entity1"> <sup> [1] </sup> </a></div> test <div class="cavacnote" entitycomment="Mr. Dryden" id="2" style="border-bottom: 2px dotted;display: inline-block; border-color: #FFA500;">test<a' + 'class="link" entitycomment_id="8" id="entity2"> <sup> [2] </sup> </a></div> test.</p></body></html>';
            // Convert and export
            console.log(html_test);
            var converted = htmlDocx.asBlob(html_test);
            saveAs(converted,  document_title + ".docx");
`

I'm using Word 2010 and I could see the red border on yours. 

Thank you for your help!

**Comment by N1kto** [comment] 2017-11-07 15:31
ok. Seems that **Word** doesn't process separate border parts settings on `<span>` elements. 
That is `<span style="border: 2px dotted #FFA500">my span text</span>` works well ( text is surrounded with dotted border from all sides). While
`<span style="border-bottom: 2px dotted #FFA500">my span text</span>` doesn't work.
Elements and their attributes support is not something we could tackle from our side. This directly depends on **Word** and its HTML rendering limitations. 
I found this [link](https://msdn.microsoft.com/en-us/library/aa338201(office.12).aspx#Word2007MailHTMLandCSS_Full) somewhat helpful when it comes to check if particular CSS is supported by **Word**.

Also, if all you want is to get some text underlined, you can use good old `<u>` element:
```
var html_test = `<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body data-id="content">
  <p>
    <u
      class="cavacnote"
      entitycomment="Annotation about Scaramouch"
      id="1"
      style="text-underline: #FFA500 dotted-heavy;"
    >
      Test
      <a class="link" entitycomment_id="2" id="entity1"><sup>[1]</sup></a>
    </u>
    test
    <u
      class="cavacnote"
      entitycomment="Mr. Dryden"
      id="2"
      style="text-underline: #FFA500 dotted-heavy;"
    >
      test
      <a class="link" entitycomment_id="8" id="entity2">
      <sup>[2]</sup>
    </a>
  </u>
test.
</p>
</body>
</html>`
```
And then:
`var converted = htmlDocx.asBlob(html_test); saveAs(converted, "test.docx");`

This should output an expected result.

`text-underline` is not a standard CSS property, it is only supported by **Word**.
If you want to know other underline styles values than that you can reverse-engineer them. Just open **Word** format the text so that it looks like you want to get it in exported, then save the file in **Word** as `.mht` file. Then if you open it in editor you will see HTML generated by **Word** with elements and CSS properties. This reverse-engineering "approach" can be also used for other cases, not for this particular one.

In the meantime I will close the issue as one that cannot be resolved by us. Also workaround was proposed.

**Closed as completed by N1kto** 2017-11-07 15:31 UTC

**Comment by george-ionita** [comment] 2017-11-07 15:51
This works great mate cheers!
