### ISSUE TITLE
Using html-docx-js with electron

### ISSUE THREAD

**Issue by aessig** [evidenceprime/html-docx-js#21] opened 2015-11-16 17:01 UTC
Hi, 
I'm using electron 0.34.2, and when I try to export a docx file, it seams to work but the docx file only contain the following: 
`[object Blob]`
Here is my code: 

```
var converted = HtmlDocx.asBlob(html_document, {orientation: 'portrait'});

fs.writeFile(path, converted, function(err) {
 if (err) throw err;
});
```

When I run the same code only using nodejs it work correctly.
Cheers

**Comment by spyshow** [comment] 2016-12-17 00:53
did you find a solution for  this ??

**Comment by N1kto** [comment] 2016-12-19 08:49
@spyshow  did you look into  #25?

**Comment by spyshow** [comment] 2016-12-21 06:46
thank you .... i didn't notice it.

**Comment by anowak** [comment] 2018-03-20 13:04
Duplicate of #25

**Closed by anowak** 2018-03-20 13:04 UTC
