### ISSUE TITLE
 I am getting fs.readFileSync is not a function error and I am not able to understand why the browser code is making a call to the 'fs' library?

### ISSUE THREAD

**Issue by abhisheknalin** [evidenceprime/html-docx-js#51] opened 2017-04-21 05:52 UTC
Works fine in Nodejs environment but doesn't work on the browser. I am using React + Webpack. My code:

```
import htmlDocx from 'html-docx-js';
import { saveAs } from 'file-saver'

exportToWord = () => {
    var content = '<!DOCTYPE html>' + '<html>' + this.state.report + '</html>'
    var converted = htmlDocx.asBlob(content);
    saveAs(converted, 'test.docx');
  }
```

When I invoke the exportToWord() function I get the following error:
```
Uncaught TypeError: fs.readFileSync is not a function
    at Object.addFiles (http://localhost/22.showReport.42adb462f5c71e04f87e.js:24685:41)
    at Object.asBlob (http://localhost/22.showReport.42adb462f5c71e04f87e.js:12695:15)
    at ShowReport._this.exportToWord2 (http://localhost/22.showReport.42adb462f5c71e04f87e.js:10579:45)
    at EnhancedButton._this.handleClick (http://localhost/app.42adb462f5c71e04f87e.js:31743:22)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost/app.42adb462f5c71e04f87e.js:2651:17)
    at executeDispatch (http://localhost/app.42adb462f5c71e04f87e.js:2437:22)
    at Object.executeDispatchesInOrder (http://localhost/app.42adb462f5c71e04f87e.js:2460:6)
    at executeDispatchesAndRelease (http://localhost/app.42adb462f5c71e04f87e.js:1854:23)
    at executeDispatchesAndReleaseTopLevel (http://localhost/app.42adb462f5c71e04f87e.js:1865:11)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost/app.42adb462f5c71e04f87e.js:2748:10)
    at Object.processEventQueue (http://localhost/app.42adb462f5c71e04f87e.js:2068:8)
    at runEventQueueInBatch (http://localhost/app.42adb462f5c71e04f87e.js:9498:19)
    at Object.handleTopLevel [as _handleTopLevel] (http://localhost/app.42adb462f5c71e04f87e.js:9509:6)
    at handleTopLevelImpl (http://localhost/app.42adb462f5c71e04f87e.js:14505:25)

```

Initially I was getting the `Can't resolve 'fs'` error which I resolved by adding
```
node: {
    fs: 'empty'
}
```
to webpack-config.

But now I am getting ` fs.readFileSync is not a function` error and I am not able to understand why the browser code is making a call to the 'fs' library?

**Comment by abhisheknalin** [comment] 2017-04-24 08:22
@N1kto @anowak any help will be greatly appreciated.

**Comment by N1kto** [comment] 2017-04-24 11:39
This issue is duplicate of #48. Please refer to solutions proposed there.

**Closed as completed by N1kto** 2017-04-24 11:39 UTC
