### ISSUE TITLE
How can we set header/footer of document ?

### ISSUE THREAD

**Issue by itsSandeepNandey** [evidenceprime/html-docx-js#71] opened 2018-02-26 15:13 UTC
Is it possible to set header & footer for the document ?

**Comment by Quixomatic** [comment] 2018-03-03 21:16
@anowak any insights on this?

**Comment by itsSandeepNandey** [comment] 2018-03-17 14:34
Not yet !!

**Comment by anowak** [comment] 2018-03-19 14:30
The problem is that Word (at least, the latest Word for Mac) doesn't seem to accept altchunks with HTML in either header or footer.

I haven't managed to make this [one work](http://sebsauvage.net/wiki/doku.php?id=word_document_generation), but I'm also skeptical regarding its compatibility with altchunks.

The bottom line is that the only way to have header/footer in the generated document would be to pass the content in WordProcessing ML, for example:

```xml
<w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:p>
    <w:pPr>
       <w:pStyle w:val="Header"/>
    </w:pPr>
    <w:r>
       <w:t>Header text</w:t>
    </w:r>
  </w:p>
</w:hdr>
```

To sum up -- it is possible, but header content cannot be specified using HTML. The easiest would be to use Word to create an empty document with a header, unzip the DOCX file and extract the definition of header/footer from it. Would such workflow suit your needs?

**Comment by anowak** [comment] 2018-03-19 14:34
Duplicate of #8 

Please see my answer there and let me know if the proposed solution would work for you.

**Closed as completed by anowak** 2018-03-19 14:34 UTC

**Comment by anowak** [comment] 2018-03-19 14:35
Duplicate of #8

**Comment by anowak** [comment] 2018-03-19 14:36
Please see my reply in #8 and let me know whether the proposed solution solves your use case 👍
